# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bcf1d313a7bc96aacab85cd7d9a34072526d273246930b37361cc7556fbebd46aa305e68f5d7147a2984b8683a79a4250ae09bc9bb4b90ca852276b6b716ee5c

test:
  secret_key_base: 0cdc7d47af37f6f0b8b09f765946104499e87850ee1fd12df35b72f59144e3811c2adfed0b26bf368d13df14c8c2285c0046e9e53de1025f314ad3dbd079c640

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
